name: main
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        target:
          [x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-20.03
      - uses: cachix/cachix-action@v8
        with:
          name: "chatgptlint"
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: |
          TARGET=${{ matrix.target }} nix develop --command just
          ls target
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: target/chatgpt-lint_${{ matrix.target }}
